<?php

/**
 * @file
 * Contains commerce_enchanced_ecommerce.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function commerce_enchanced_ecommerce_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the commerce_enchanced_ecommerce module.
    case 'help.page.commerce_enchanced_ecommerce':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Send data to google enchanced ecommerce.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function commerce_enchanced_ecommerce_preprocess_commerce_product(&$variables) {
  $elements = $variables['elements'];
  if ($elements['#view_mode'] == 'full') {
    /** @var \Drupal\commerce_product\Entity $product */
    $product = $elements["#commerce_product"];
    $details = \Drupal::service('commerce_enchanced_ecommerce.get_data')->getProductData($product);
    $variables['#attached']['library'][] = 'commerce_enchanced_ecommerce/product_details';
    $variables['#attached']['drupalSettings']['commerceEnchancedECommerce'] = $details;
  }
  if ($elements['#view_mode'] == 'teaser') {
    /** @var \Drupal\commerce_product\Entity $product */
    $product = $elements["#commerce_product"];
    $variable = $product->getDefaultVariation();
    $variables['attributes']['data-variation'] = $variable->getTitle();
    $details = \Drupal::service('commerce_enchanced_ecommerce.get_data')->getProductData($product);
    $variables['attributes']['data-sku'] = $details->id;
    if ($product->hasField('field_category') && !$product->field_category->isEmpty() && !is_null($product->field_category->entity)) {
      $variables['attributes']['data-category'] = $product->field_category->entity->getName();
    }
    if ($product->hasField('field_brand') && !$product->field_brand->isEmpty() && !is_null($product->field_brand->entity)) {
      $variables['attributes']['data-brand'] = $product->field_brand->entity->getName();
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function commerce_enchanced_ecommerce_form_alter(&$form, FormStateInterface &$form_state, $form_id) {
  if (strpos($form_id, 'commerce_order_item_add_to_cart_form_commerce_product') !== FALSE) {
    $form['#attached']['library'][] = 'commerce_enchanced_ecommerce/add_to_cart';
    /** @var \Drupal\commerce_order\Entity\OrderItemInterface $orderItem */
    $orderItem = $form_state->getFormObject()->getEntity();
    $details = \Drupal::service('commerce_enchanced_ecommerce.get_data')->getCartProductData($orderItem);
    /** @var \Drupal\commerce_store\Entity\Store $store */
    $store = \Drupal::service('commerce_store.current_store')->getStore();
    $details->currencyCode = $store->getDefaultCurrencyCode();
    $form['#attached']['drupalSettings']['ceeAddToCart'] = $details;
  }
  if (strpos($form_id, '_cart_form') !== FALSE) {
    $form['#attached']['library'][] = 'commerce_enchanced_ecommerce/remove_from_cart';
    $carts = \Drupal::service('commerce_cart.cart_provider')->getCarts();
//    if (!empty($carts)) {
//     $products = [];
//     foreach ($carts as $cart_id => $cart) {
//        if (isset($form[$cart_id])) {
//          $items = &$form[$cart_id]['shipments'][0]['content']['#shipment_items'];
//          foreach ($items as &$item) {
//            $variant = $item['purchased_entity']['#commerce_product_variation'];
//            $product = $variant->getProduct();
//            $enchanchedEcommerce = new EnchancedECommerce($product, $variant);
//            $products[$variant->id()] = $enchanchedEcommerce->getCartActionDetails();
//          }
//        }
//      }
//      $form['#attached']['drupalSettings']['ceeRemoveFromCart'] = $products;
//    }
  }
  if (strpos($form_id, 'commerce_checkout_flow') !== FALSE && $form_id !== 'commerce_checkout_flow_edit_form') {
    /** @var \Drupal\commerce_order\Entity\OrderInterface $order */
    $order = $form_state->getFormObject()->getOrder();
    $stepId = $form['#step_id'];
    if ($stepId === 'complete') {
      \Drupal::service('commerce_enchanced_ecommerce.get_data')->getOrderComplete($order, $form);
    }

    $products = [];
    foreach ($order->get('shipments') as $shipmentListItem) {
      /** @var \Drupal\interflora_shipping\Entity\Shipment $shipment */
      $shipment = $shipmentListItem->entity;
      foreach ($shipment->getItems() as $shipmentItem) {
        $products[] = \Drupal::service('commerce_enchanced_ecommerce.get_data')->getShipmentProduct($shipmentItem, $shipment);
      }
    }

    $payload = \Drupal::service('commerce_enchanced_ecommerce.get_data')->getCheckoutStep($stepId, $products);
    if ($payload->stepIdToNumber($stepId) !== FALSE) {
      $form['#attached']['drupalSettings']['checkout'] = $payload;
      $form['#attached']['drupalSettings']['stepId'] = $stepId;
      $form['#attached']['library'][] = 'commerce_enchanced_ecommerce/checkout';
    }
  }
}
